version: '3.1'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8081:8080
